services:
  ui:
    build:
      context: ./websrc
      dockerfile: Dockerfile
    image: "text-to-sql-ez-picard-ui:latest"
    ports:
      - '8501:8501'
    volumes:
      - type: bind
        source: "./database"
        target: /database
    depends_on:
      - api

  api:
    image: "tscholak/text-to-sql-eval:6a252386bed6d4233f0f13f4562d8ae8608e7445"
    command: sh -c "cp /app/src/* /app/seq2seq/;pip install -r /app/seq2seq/requirements.txt ; python seq2seq/serve_seq2seq.py configs/serve.json"
    user: "13011:13011"
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: "./database"
        target: /database
      - type: bind
        source: "./transformers_cache"
        target: /transformers_cache
      - type: bind
        source: "./configs"
        target: /app/configs
      - type: bind
        source: "./src"
        target: /app/src
    # depends_on:
    #   - mysql
    
  mysql:
    build: ./mysql
    ports:
     - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'Chinook'
    